### PR TITLE
Add workspace/configuration handling

### PR DESCRIPTION
**Pull request by ainar-g**
After receiving workspace/didChangeConfiguration some servers will
request the full updated configuration from the client using
workspace/configuration instead of reading the changed configuration
section clients have sent them.  So, support this capability and respond
with a workspace configuration if there is one.

See also: golang/go#41311.

### CODE REVIEW

**Comment by ainar-g** [comment]
<p>This is my first PR to&#xA0;<code>vim-lsc</code>, so&#xA0;if&#xA0;you see
anything wrong, please tell me.&#x2003;Thanks!</p>

**Comment by natebosch** [comment]
@ainar-g sorry for the long delay in reviewing.

I implemented the support for requesting multiple sections since I do think it is worth having that from the start.

I am worried about https://github.com/microsoft/language-server-protocol/issues/972 and whether different servers are going to need additional information in the config to handle these behavior variations. It might be fine to wait and see if that comes up for folks.

Can you try this out and let me know if it works for you?

**Comment by ainar-g** [comment]
@natebosch, thanks, but I'll only be able to check it out in early January, because I've deleted my old configs when I switched to Neovim unstable with native LSC support.  Feel free to merge either way!

**Comment by natebosch** [comment]
Sounds good. I'll go ahead and merge since my small amount of manual testing seems OK so far.

Thanks!

**Review by natebosch — APPROVED** [review]

**Pull request merged**
