### PR TITLE
vim-rooter support

### PR DESCRIPTION
**Pull request by adelarsq**
Adding [vim-rooter](https://github.com/airblade/vim-rooter) support.

### CODE REVIEW

**Comment by natebosch** [comment]
Looks interesting. Thanks!

I'll give this some consideration. I'm not sure I'd like to hardcode support for this particular plugin, but there are some other ways we could go about this:
- Allow a global configuration to override how the rootUri is found
- Allow a per-server configuration to override how the rootUri is found

I think both of these would be pretty easy to implement. The latter is more flexible but could be more annoying to configure if many servers end up wanting to use the same override...

**Comment by natebosch** [comment]
Actually, come to think of this we can probably use https://github.com/natebosch/vim-lsc/commit/4e537fa0d2e126bfe0a089f631e129e656544a76

```viml
function! OverrideRootUr(method, params) abort
  let params.rootUri = exists('g:loaded_rooter')? FindRootDirectory() : getcwd()
  return params
endfunction

let g:lsc_server_commands  = {
    \ 'something' : {
    \    'command': 'some-command',
    \    'message_hooks': {
    \        'initialize': function('OverrideRootUri')
    \    }
    \}
```

Does that work for you?

**Comment by adelarsq** [comment]
Works, but shows this message on initialization:
```
[lsc:Error] Failed to run message hook for initialize
[lsc:Error] Could not decode message:
[lsc:Error] Error dispatching message: 'Vim(if):E715: Dictionary required'
```

**Comment by natebosch** [comment]
Ah, I have a bug in my function - I'm missing the `a:` prefix to refer to arguments.

```viml
function! OverrideRootUr(method, params) abort
  let a:params.rootUri = exists('g:loaded_rooter')? FindRootDirectory() : getcwd()
  return a:params
endfunction
```

**Comment by adelarsq** [comment]
Still shows the same error. Now the server starts, but after some time stops:
image
I'm trying to use with the [Java Language Server](https://github.com/eclipse/eclipse.jdt.ls).

**Comment by natebosch** [comment]
I pushed https://github.com/natebosch/vim-lsc/commit/07cd8c44735e59acbb6289b58372070ba89f286f which should give us more info on the failure. Can you update and try again?

**Comment by adelarsq** [comment]
image
Strange that using only ``params`` instead of ``a:params`` the server starts 😮

**Comment by natebosch** [comment]
Can you also paste in the function that you wrote for this? Looks like yours differs from mine if you have an `echo` in there... The particular error looks like you might be doing `echo a:params` instead of `echo string(a:params)` (or `echo 'something '.a:params` instead of `echo 'something '.string(a:params)`)

**Comment by natebosch** [comment]
> Strange that using only ``params`` instead of ``a:params`` the server starts 😮 

What was happening here is:
- message hook runs but when it refers to `params` it fails and nothing is changed, vim-lsc catches the exception and goes through with the default call

When updated to `a:params`:
- something else throws, but the original `dict` is modified so even though vim-lsc catches the exception the call it makes has a modified `rootUri`.
- We have yet another bug in how we're setting the URI. We should be using `lsc#uri#documentUri`. Since we aren't the server is probably failing to understand the initialize call.

Sorry for the churn on this...
I think what we want is:

```viml
function! OverrideRootUr(method, params) abort
  let root_uri = exists('g:loaded_rooter')? FindRootDirectory() : getcwd()
  let a:params.rootUri = lsc#uri#documentUri(root_uri)
  return a:params
endfunction
```

**Comment by adelarsq** [comment]
Nice. Did work. I will do more tests later today.

**Comment by adelarsq** [comment]
Rust Language Server don't use any argument on command line, just the actual path:
```
C:\workspace\ws_rust\Teste1 {git}{hg}
{lamb} rustup run beta rls .
Unknown argument '.'. Supported arguments:

    --version or -V to print the version and commit info
    --help or -h for this message
    --cli starts the RLS in command line mode
    No input starts the RLS as a language server
```
It's possible using the method above to avoid pass parameters to it?

**Comment by natebosch** [comment]
> Rust Language Server don't use any argument on command line, just the actual path

When vim-lsc runs the command it will only ever run the command you gave it - it doesn't add any additional parameters. Is there an issue with the `g:lsc_server_commands` config which is using an argument that it shouldn't?

**Comment by adelarsq** [comment]
@natebosch Yes. I think that isn't starting because of that. For Python and Java it's working fine now. I still didn't have time to see #60.

**Comment by natebosch** [comment]
Sounds good. Will wait for followup on the docker server issue over on that thread.

Thanks!

**Comment by natebosch** [comment]
As an FYI after #64 this can have a bit nicer syntax:

```viml
let g:lsc_server_commands  = {
    \ 'something' : {
    \    'command': 'some-command',
    \    'message_hooks': {
    \        'initialize': {'rootUri': {method, params ->
    \            lsc#uri#documentUri(exists('g:loaded_rooter') ? FindRootDirectory() : getcwd())}},
    \    }
    \}
```

Or since its in a personal config if you always expect to have `rooter`:

```viml
let g:lsc_server_commands  = {
    \ 'something' : {
    \    'command': 'some-command',
    \    'message_hooks': {
    \        'initialize': {'rootUri': {method, params ->
    \            lsc#uri#documentUri(FindRootDirectory())}},
    \    }
    \}
```

**Pull request closed without merging**
