### PR TITLE
support initializeOptions param to servers via initialization_options in config dict

### PR DESCRIPTION
**Pull request by razamatan**
needed for cquery support.

### CODE REVIEW

**Comment by natebosch** [comment]
You should be able to accomplish the same thing today with something like:

```viml
function! AddInitializationOptions(method, params) abort
  let a:params.initializationOptions = {...}
  return a:params
endfunction

let g:lsc_server_commands = {
  \ 'some_lang' : {
  \    'command': 'some_command',
  \    'message_hooks': {
  \      'initialize': function('AddInitializationOptions'),
  \    }
  \  }
  \}
````

We could also make this easier with https://github.com/natebosch/vim-lsc/issues/64

**Comment by razamatan** [comment]
seems like an unnecessary abstraction to support something that's formally in the lang server spec for the initialize request.

**Comment by natebosch** [comment]
> seems like an unnecessary abstraction to support something that's formally in the lang server spec for the initialize request.

I definitely agree that the function adds too much boilerplate. How do you feel if we get #64 and the config looks instead like:

```viml
let g:lsc_server_commands = {
  \ 'some_lang' : {
  \    'command': 'some_command',
  \    'message_hooks': {
  \      'initialize': {'initializationOptions': {...}},
  \    }
  \  }
  \}
```

**Comment by razamatan** [comment]
what is the design of the server_commands registration?  vim-lsp went with trying to surface more of the initialize parameters directly to the user.  is being a "thin" interface to the lang server protocol a design goal?  if not, then #64 is a fine workaround.

**Comment by natebosch** [comment]
My goal is to have 'hardcoded' support for the minimum to get any server working and to open up (hopefully easy) points of extension to get other servers working.

I explicitly want to avoid any references within this plugin to non-standard stuff. As you pointed out `initalizationOptions` is standard in the spec, so it would be fine to have knowledge of it here - but unless we think the majority of users are going to need it I like the idea of making it possible to set but not putting in specific support.

I also think that the syntax difference between an explicit key and what we can get with #64 is minor.

Will close this for now.

**Comment by razamatan** [comment]
for the cquery lang server, setting something in initializationOptions is required to get things working.

**Comment by natebosch** [comment]
Ok, the change is in now.

You should be able to configure as described above:

```viml
let g:lsc_server_commands = {
  \ 'some_lang' : {
  \    'command': 'some_command',
  \    'message_hooks': {
  \      'initialize': {'initializationOptions': {...}},
  \    }
  \  }
  \}
```

I do agree that this is important to be able to configure - especially since some servers like cquery require it - the consideration is mostly around what we want the config to look like. With your change we essentially remove a level or 2 of nesting which I don't think buys us much now that we don't have the function syntax getting in the way.

I might consider at some point dropping the `lsc_trace_level` config variable as well since I like having fewer ways to do things and I don't mind pushing a little knowledge of LSC into the configuration.

```viml
let g:lsc_server_commands = {
  \ 'some_lang' : {
  \    'command': 'some_command',
  \    'message_hooks': {
  \      'initialize': {'trace_level': 'verbose'},
  \    }
  \  }
  \}
```

Thanks so much for the discussion and for the initial pull request!

**Comment by razamatan** [comment]
thanks.

i do think it's somewhat important to push LSC concepts more to the user.  my personal take is that lsc is a standard, so vim-lsc shouldn't try and hide it.

**Pull request closed without merging**
