### PR TITLE
Improved hover popup & float window

### PR DESCRIPTION
**Pull request by bluz71**
Ongoing work on hovering (again).

For Neovim:

- Limit width to a max of 95% of the screen width. This ends up being
  visually pleasing (and more akin to what Vim popups look like)

- To fix overflow issues, the max height of the float should be based on
  the window height not the screen height. Horizontal split windows
  broke my previous float up or float down sizing logic. Now that is no
  longer an issue.

For Vim (8.2):

- Added in scrolling support.

- This proved very painful since popups should work all that out by
  itself, but doesn't.

- Scrolling support comes in via setting the 'maxheight' attribute. But
  that attribute needs to be set very carefully.

- Lots of magic involved, basically the result of much trial and error,
  I spent two days on this.

- The only way I could figure out how to set 'maxheight' correctly was
  to create an invisible popup, figure out if it poped up or down (to
  the extreme screen edge) and then set 'maxheight' to the visible popup
  size.

- Some corner cases are not handled perfectly, such as when a screen is
  split vertically a few times and hover is done on the extreme right
  sliver.

I am not entirely happy with the look of the code.

But I am quite happy with the actual hover behaviour, scrolling (in Vim,
missing previously) is a big improvement.

### CODE REVIEW

**Comment by bluz71** [comment]
Nate,

Please have a play in both Vim (version 8.2) and Neovim.

I have lost sleep trying to figure out how to do scrolling in Vim Popups.

I looked and looked, and found nothing. The docs make it seem Vim would work that out automatically, but that is not my experience. The `maxheight` attribute is what does it, and it's insane how fiddly that value is, if you get that value wrong then you end up with a scrollbar that will not reach all the way to the bottom of the content.

Cheers.

**Comment by bluz71** [comment]
Flutter API has extensive hover content, for example `Colors`.
That was what I testing with.

**Comment by natebosch** [comment]
The stuff about keeping the width at 95% looks good - we can probably get that merged right away if you want to pull that out into a separate PR.

The hack for vim looks rough... I wonder if we're swimming upstream too much here. I'm also getting a bit nervous about the maintenance burden of this code around the popup windows.

Since I migrated over to the popup workflow over the preview window workflow I've also felt something else missing, which is being able to keep the documentation on screen as I move my cursor around. I had been considering looking for a way to add a new shortcut that either forces the preview window or the popup from the beginning, or maybe some way to "move" what's in the popup to the preview window.

Maybe we should consider reusing `K` for that - the first `K` opens the popup, then on the next we check and see that the popup is open already and move the content over to the preview window. Once it's in the preview window the user can manage it how they like - they can make the window whatever size they want and scroll around at will. They can leave it open as they move the cursor around, and close it with `<c-w>z`.

What do you think?

**Comment by bluz71** [comment]
The Vim implementation is bad. I hate it, and to be honest I am relieved it is being rejected.

Not having a scrollable popup was bothersome from a completeness perspective (in my mind).
But, I use Neovim, which has had scrollable floats since my last PR.
I am fine with that being dumped. To be honest, Vim itself should figure out scrollability automatically, but currently doesn't. I think the Vim popup implementation has flaws.

I still wish there was a way to scroll the Vim popup.

I can submit a new Neovim 95% patch. However, I would also advise bundling that with my other Neovim fix to use window heights rather than screen heights otherwise overflows will result with horizontal split windows. 

I can do all that. I will submit a new PR soon.

Your double `K` suggestion sounds good. Should be doable based on whether a popup/float is already on the screen, if so display in the preview. Yes, that seems a worthwhile enhancement. Heck it somewhat fixes the Vim non-scrolling issue, just do a double `K` and scroll in the preview window.

**Pull request closed without merging**
